name: Gitleaks Secret Scan

on:
  push:
    branches:
      - Dev
      
jobs:
  gitleaks_scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for complete scanning

      - name: Install Gitleaks
        run: |
          curl -sSL -o gitleaks.tar.gz https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz
          tar -xvzf gitleaks.tar.gz
          chmod +x gitleaks
          mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        run: |
          gitleaks detect --redact -v --exit-code=2 --report-format=sarif --report-path=gitleaks-results.sarif

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results.sarif
          path: gitleaks-results.sarif