name: MegaLinter

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  mega-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run MegaLinter
        uses: oxsecurity/megalinter-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
