name: MegaLinter

on:
  push:
    branches:
      - dev

jobs:
  lint:
    name: Run MegaLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run MegaLinter
        uses: oxsecurity/megalinter@v6
